### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by JesterX69** [demonlexe/HowrseAdvisor#1]
The extension not doing what it spoused to do,
simply not working

**Comment by demonlexe** [comment]
Hi there JesterX69, just saw this!

Fixed this issue, assuming that the issue was you never opened the extension UI 
(This can be done by going to Extensions, HowrseAdvisor, pinning it, then clicking on the plugin icon.)

There is a settings page inside the plugin to enable features. By default, it wasn't doing anything unless the user opens the settings window.

Now, it will load the defaults automatically after you add the plugin..
But you should still open the plugin settings because I have multiple features added that are disabled by default in case they are unwanted by users.
